# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: dev
type: Opaque
data:
  # 值需要base64编码
  # password -> cGFzc3dvcmQ=
  pg-user: YWRtaW4=
  pg-pass: cGFzc3dvcmQ=
  redis-pass: cmVkaXNQc3c=