spring:
  #数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?characterEncoding=utf-8&useSSL=false
    username: developer
    password: 123456
    hikari:
      minimum-idle: 2
      maximum-pool-size: 200